//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Партнеры
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materials()
        {
            this.SupplyHistory = new HashSet<SupplyHistory>();
            this.Warehouse = new HashSet<Warehouse>();
        }
    
        public int material_id { get; set; }
        public Nullable<int> material_type_id { get; set; }
        public string material_name { get; set; }
        public Nullable<int> supplier_id { get; set; }
        public int quantity_per_package { get; set; }
        public string unit_of_measure { get; set; }
        public string description { get; set; }
        public string image_url { get; set; }
        public decimal cost { get; set; }
        public int quantity_in_stock { get; set; }
        public int min_allowed_quantity { get; set; }
    
        public virtual MaterialType MaterialType { get; set; }
        public virtual Suppliers Suppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplyHistory> SupplyHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Warehouse> Warehouse { get; set; }
    }
}
