//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Партнеры
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personnel
    {
        public int personnel_id { get; set; }
        public Nullable<int> employee_id { get; set; }
        public string equipment_access { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
