//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Партнеры
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesHistory
    {
        public int sale_id { get; set; }
        public Nullable<int> partner_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public int quantity { get; set; }
        public System.DateTime sale_date { get; set; }
    
        public virtual Partners Partners { get; set; }
        public virtual Products Products { get; set; }
    }
}
