//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Партнеры
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplyHistory
    {
        public int supply_id { get; set; }
        public Nullable<int> supplier_id { get; set; }
        public Nullable<int> material_id { get; set; }
        public int quantity { get; set; }
        public System.DateTime supply_date { get; set; }
    
        public virtual Materials Materials { get; set; }
        public virtual Suppliers Suppliers { get; set; }
    }
}
