//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Партнеры
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse
    {
        public int warehouse_id { get; set; }
        public Nullable<int> material_id { get; set; }
        public int quantity_received { get; set; }
        public int quantity_reserved { get; set; }
        public int quantity_issued { get; set; }
        public int quantity_written_off { get; set; }
    
        public virtual Materials Materials { get; set; }
    }
}
